### PR TITLE
Set version to `1.0.5`

### PR DESCRIPTION
**Pull request by shadeMe**
### Types of change

Chore

## Checklist

- [x] I confirm that I have the right to submit this contribution under the project's MIT license.
- [ ] I ran the tests, and all new and existing tests passed.
- [ ] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by adrianeboyd** [comment]
Why v1.1.0?

**Comment by shadeMe** [comment]
> Why v1.1.0?

Oh, I wasn't sure if the changes warranted a new major release. Happy to change it to `2.0.0`.

**Comment by adrianeboyd** [comment]
I expected it to be v1.0.5, but are there changes that warrant a new minor version? (Usually for these packages there aren't?)

**Comment by shadeMe** [comment]
We [added](https://github.com/explosion/spacy-loggers/commits/main/) 4 new loggers and updated most of the existing ones.

**Comment by adrianeboyd** [comment]
But none of the old ones should break, so I think it should be v1.0.5? Similar to `spacy-legacy`, which is still on v3.0.x.

**Comment by shadeMe** [comment]
Ok, changed to `1.0.5`.

**Pull request merged**
